### ISSUE TITLE
此版本不支持该平台问题

### ISSUE THREAD

**Issue by Pepste2** [VanXNF/Hackintosh-Ryzen-3500X-MSI-B450M-Mortar-MAX#1]
在我参考了各大论坛AMD OS X上的帖子之后，决定动手装一台黑苹果，u盘，BIOS设置各种搞完之后，进oc发现扫描不到macos的镜像文件，只显示一个重置nvram，然后我使用vscode进行修改config文件，修改security里参数为0即可扫描全部，再次进入系统发现有了，但是一个新的问题出现，在o'c选项栏中点击安装macos时提示此版本不支持该平台，我使用的镜像为黑果小兵macOS-Catalina10.15.6（19G2006），在使用balenaEtcher制作好u盘，发现有三分区，我删除了efi和wepe（微pe），只保留下oc分区，进行了文件替换，再次进入还是如此，我在黑苹果qq讨论群碰到一位大佬，他给了我amd的efi文件oc引导的，成功进入安装界面，驱动都很完全，但是键盘很鼠标都不是很跟手，打字有时出现叠字，按了没反应等等，我在想作者能不能给我一个你的镜像文件，让我尝试一下能否安装成一个“完美”的黑苹果
---------萌新折腾黑果的道路

> 第一次装时尝试了2018年的教程，引导方式为clover，采用amd替换内核的方式来安装黑苹果，但是装完进入黑苹果初始化设置就黑屏，我起先怀疑是否显卡驱动kext没安装，去github上下载了whatevergreen.kexts，但是我不知道怎么使用，放入others文件夹，重新进入系统，不起作用，我也不知道怎么编辑config文件，amd，yes，黑果不yes了

> 配置几乎和作者是一模一样，不是几乎是真的一模一样

[错误1](https://s1.ax1x.com/2020/08/08/aoE3Nj.jpg)
[错误2](https://s1.ax1x.com/2020/08/08/aoE84s.jpg)
[关于本机](https://s1.ax1x.com/2020/08/08/aoEwbF.png)
图片访问可能有点慢
我喜欢折腾，我很有耐心，求指导
> 镜像文件链接：https://blog.daliansky.net/macOS-Catalina-10.15.6-19G73-Release-version-with-Clover-5119-original-image-Double-EFI-Version-UEFI-and-MBR.html

**Comment by Pepste2** [comment]
对于一个接触黑苹果不到三天的萌新来说已经超出我的认知了，求作者推荐科普或了解黑苹果的博客或视频

**Comment by VanXNF** [comment]
你对这个了解较少的话，可以先在B站搜索一下司波图的AMD黑苹果视频，大概是今年三月份的一个视频，可以帮你大概了解A平台黑苹果流程，40分钟左右，建议完整观看。如果想要精进且英语尚可的话建议还是阅读一下我鸣谢列表第二个网址里的AMD相关内容(使用浏览器翻译也可)，这个也是我目前找到的AMD黑苹果最完善的资料了。我的镜像是使用开源项目 gibMacOS 制作的，如果还有问题请留言。

**Comment by VanXNF** [comment]
针对键盘和鼠标的话我建议你插在机箱后部的接口，然后定制一下Hackintool软件定制一下USB端口，把它们内建后会好很多。至于鼠标在mac下往往会发飘，这是因为mac系统给它设了加速度的关系，可以参考这个网址里的软件来解决https://sspai.com/post/40596 我实际使用了一下确实有效。AMD Ryzen平台确实是有通用配置的，但是你想要追求完美的话还是要进行各种个性化定制的。SSDT定制可以参考鸣谢列表第三个网址。

**Comment by VanXNF** [comment]
安装时提示此版本不支持该平台系未注入机型及三码导致，请自行添加

**Comment by Pepste2** [comment]
好的，谢谢！我尝试一下定制USB ports能否解决键盘打字问题
